# Анализ лояльности пользователей Яндекс Афиши

### Цели и задачи проекта

<font color='#777778'>**Цель:** Провести исследовательский анализ данных лояльности пользователей сервиса "Яндекс Афиша", чтобы понять, какие пользователи с большей вероятностью возвращаются на платформу и делают заказы повторно.   

**Задачи:**
1. Загрузить данные и познакомиться с их содержимым.
2. Провести предобработку данных.
3. Описать профиль пользователя
4. Исследовать признаки, влияющие на совершение повторного заказа пользователями.
5. Сформулировать общий вывод и рекомендации

</font>

## Содержимое проекта
#### Оглавление

1. <a href="#section1">Загрузка данных</a>
2. <a href="#section2">Предобработка данных</a>
3. <a href="#section3">Создание профиля пользователя</a>
4. <a href="#section4">Исследовательский анализ данных</a>
    
    4.1 <a href="#section41">Исследование признаков первого заказа и их связи с возвращением на платформу</a>
    
    4.2 <a href="#section42">Исследование поведения пользователей через показатели выручки и состава заказа</a>
    
    4.3 <a href="#section43">Исследование временных характеристик первого заказа и их влияния на повторные покупки</a>
    
    4.4 <a href="#section44">Корреляционный анализ количества покупок и признаков пользователя</a>

5. <a href="#section5">Выводы и рекомендации</a>
---

<a id="section1"></a>

## Этапы выполнения проекта

### 1. Загрузка данных и их предобработка
---

**Задача 1.1:** Напишите SQL-запрос, выгружающий в датафрейм pandas необходимые данные. 

<u>Параметры для подключения к базе данных заданы в connection.env</u>

Для выгрузки используйте запрос из предыдущего урока и библиотеку SQLAlchemy.

Выгрузка из базы данных SQL должна позволить собрать следующие данные:

- `user_id` — уникальный идентификатор пользователя, совершившего заказ;
- `device_type_canonical` — тип устройства, с которого был оформлен заказ (`mobile` — мобильные устройства, `desktop` — стационарные);
- `order_id` — уникальный идентификатор заказа;
- `order_dt` — дата создания заказа (используйте данные `created_dt_msk`);
- `order_ts` — дата и время создания заказа (используйте данные `created_ts_msk`);
- `currency_code` — валюта оплаты;
- `revenue` — выручка от заказа;
- `tickets_count` — количество купленных билетов;
- `days_since_prev` — количество дней от предыдущей покупки пользователя, для пользователей с одной покупкой — значение пропущено;
- `event_id` — уникальный идентификатор мероприятия;
- `service_name` — название билетного оператора;
- `event_type_main` — основной тип мероприятия (театральная постановка, концерт и так далее);
- `region_name` — название региона, в котором прошло мероприятие;
- `city_name` — название города, в котором прошло мероприятие.

---

In [1]:
# Импортируем необходимые библиотеки
# Импорт pandas
import pandas as pd

# Импорт sqlalchemy
from sqlalchemy import create_engine

# Импорт load_dotenv.
from dotenv import load_dotenv

# Импорт библиотеки для работы с окружением.
import os

In [2]:
# Загрузка переменных из connetion.env
load_dotenv(dotenv_path='connection.env')

host = os.getenv('HOST')
database = os.getenv('DATABASE')
port = os.getenv('PORT')
auth = os.getenv('AUTH')
user = os.getenv('USER')
password = os.getenv('PASSWORD')

In [3]:
# Создаем config для подключения
db_config = {'user': user, 
             'pwd': password, 
             'host': host,
             'port': port, 
             'db': database
             }

# Формируем строку к подключению
connection_string = 'postgresql://{}:{}@{}:{}/{}'.format(
    db_config['user'],
    db_config['pwd'],
    db_config['host'],
    db_config['port'],
    db_config['db'],
)

# Создаем подключение
engine = create_engine(connection_string)

In [4]:
# Формируем запрос к данным
query = '''
WITH set_config_precode AS (
  SELECT set_config('synchronize_seqscans', 'off', true)
)

select 
  user_id,
  p.device_type_canonical,
  p.order_id,
  p.created_dt_msk AS order_dt,
  p.created_ts_msk AS order_ts,
  p.currency_code,
  p.revenue,
  p.tickets_count,
	cast(p.created_dt_msk as date)- cast(LAG(p.created_dt_msk ) over (partition by p.user_id  order by p.created_dt_msk) as date) as days_since_prev,
  p.event_id,
  p.service_name,
  e.event_type_main,
  r.region_name,
  c.city_name
from afisha.purchases p
left join afisha.events as e ON p.event_id=e.event_id
left join afisha.city as c ON e.city_id=c.city_id
left join afisha.regions as r ON c.region_id=r.region_id
where 
  (p.device_type_canonical = 'mobile' 
  OR p.device_type_canonical = 'desktop')
  AND e.event_type_main != 'фильм'
order BY p.user_id
'''

In [5]:
# Создаем датафрейм для работы
df = pd.read_sql_query(query, con=engine)

In [6]:
# Cоздаем копию датасета до преобразования для возможности проверить сделанные изменения после предобработки
temp = df.copy() 
len(temp)

290611

---

**Задача 1.2:** Изучите общую информацию о выгруженных данных. Оцените корректность выгрузки и объём полученных данных.

Предположите, какие шаги необходимо сделать на стадии предобработки данных — например, скорректировать типы данных.

Зафиксируйте основную информацию о данных в кратком промежуточном выводе.

---

In [7]:
df.head(10)

,user_id,device_type_canonical,order_id,order_dt,order_ts,currency_code,revenue,tickets_count,days_since_prev,event_id,service_name,event_type_main,region_name,city_name
0,0002849b70a3ce2,mobile,4359165,2024-08-20,2024-08-20 16:08:03,rub,1521.94,4,NaN,169230,Край билетов,театр,Каменевский регион,Глиногорск
1,0005ca5e93f2cf4,mobile,7965605,2024-07-23,2024-07-23 18:36:24,rub,289.45,2,NaN,237325,Мой билет,выставки,Каменевский регион,Глиногорск
2,0005ca5e93f2cf4,mobile,7292370,2024-10-06,2024-10-06 13:56:02,rub,1258.57,4,75.0,578454,За билетом!,другое,Каменевский регион,Глиногорск
3,000898990054619,mobile,1139875,2024-07-13,2024-07-13 19:40:48,rub,8.49,2,NaN,387271,Лови билет!,другое,Североярская область,Озёрск
4,000898990054619,mobile,972400,2024-10-04,2024-10-04 22:33:15,rub,1390.41,3,83.0,509453,Билеты без проблем,стендап,Озернинский край,Родниковецк
5,000898990054619,mobile,2613713,2024-10-23,2024-10-23 15:12:00,rub,902.74,3,19.0,500862,Облачко,концерты,Лугоградская область,Кристалевск
6,00096d1f542ab2b,desktop,6636941,2024-08-15,2024-08-15 16:48:48,rub,917.83,4,NaN,201953,Край билетов,театр,Каменевский регион,Глиногорск
7,000a55a418c128c,mobile,4657981,2024-09-29,2024-09-29 19:39:12,rub,47.78,1,NaN,265857,Лучшие билеты,театр,Поленовский край,Дальнозолотск
8,000a55a418c128c,mobile,4657952,2024-10-15,2024-10-15 10:29:04,rub,74.84,2,16.0,271579,Лучшие билеты,театр,Поленовский край,Дальнозолотск
9,000cf0659a9f40f,mobile,6818017,2024-06-20,2024-06-20 10:35:26,rub,1421.91,4,NaN,516728,Лови билет!,концерты,Широковская область,Радужнополье

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 290611 entries, 0 to 290610
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   user_id                290611 non-null  str
 1   device_type_canonical  290611 non-null  str
 2   order_id               290611 non-null  int64
 3   order_dt               290611 non-null  datetime64[us]
 4   order_ts               290611 non-null  datetime64[us]
 5   currency_code          290611 non-null  str
 6   revenue                290611 non-null  float64
 7   tickets_count          290611 non-null  int64
 8   days_since_prev        268678 non-null  float64
 9   event_id               290611 non-null  int64
 10  service_name           290611 non-null  str
 11  event_type_main        290611 non-null  str
 12  region_name            290611 non-null  str
 13  city_name              290611 non-null  str
dtypes: datetime64[us](2), float64(2), int64(3), str(7)
memory usage: 31.0 MB

In [9]:
df.describe()

,order_id,order_dt,order_ts,revenue,tickets_count,days_since_prev,event_id
count,2.906110e+05,290611,290611,290611.000000,290611.000000,268678.000000,290611.000000
mean,4.326225e+06,2024-09-01 22:36:38.741272,2024-09-02 13:31:19.397731,625.584360,2.754311,3.222381,438019.834992
min,1.000000e+00,2024-06-01 00:00:00,2024-06-01 00:00:42,-90.760000,1.000000,0.000000,4436.000000
25%,2.163618e+06,2024-07-30 00:00:00,2024-07-30 11:53:37.500000,116.850000,2.000000,0.000000,361772.000000
50%,4.326366e+06,2024-09-12 00:00:00,2024-09-12 14:02:10,356.010000,3.000000,0.000000,498275.000000
75%,6.488330e+06,2024-10-09 00:00:00,2024-10-09 15:57:55.500000,810.130000,4.000000,1.000000,546287.000000
max,8.653108e+06,2024-10-31 00:00:00,2024-10-31 23:59:54,81174.540000,57.000000,148.000000,592325.000000
std,2.497551e+06,NaN,NaN,1227.693064,1.170620,11.350509,147423.078841

In [10]:
# Первичный анализ данных
count_first_order = df['days_since_prev'].isna().sum()
print(f"""
Количество уникальных пользователей: {df['user_id'].nunique()}
Количество первых заказов: {count_first_order}
Количество уникальных заказов: {df['order_id'].nunique()}
Доля первых заказов составляет: {round(count_first_order/len(df)*100,2)}
Количество заказов с выручкой равно 0 составляет: {len(df[df['revenue'] == 0])} или {round(len(df[df['revenue'] == 0])/len(df)*100,2)}%
Количество заказов с выручкой ниже 0 составляет: {len(df[df['revenue'] < 0])} или {round(len(df[df['revenue'] < 0])/len(df)*100,2)}%
""")

Количество уникальных пользователей: 21933
Количество первых заказов: 21933
Количество уникальных заказов: 290611
Доля первых заказов составляет: 7.55
Количество заказов с выручкой равно 0 составляет: 5526 или 1.9%
Количество заказов с выручкой ниже 0 составляет: 381 или 0.13%

In [11]:
device_type = df['device_type_canonical'].sort_values().unique().tolist()
device_type

['desktop', 'mobile']

In [12]:
event_type = df['event_type_main'].sort_values().unique().tolist()
event_type

['выставки', 'другое', 'концерты', 'спорт', 'стендап', 'театр', 'ёлки']

In [13]:
curr_code  = df['currency_code'].sort_values().unique().tolist()
curr_code

['kzt', 'rub']

##### Промежуточный вывод

* Всего в датафрейме содержится 290611 строк, пропуски встречаются только в столбце `days_since_prev`, который был добавлен на этапе формирования данных (SQL запроса). Значение NULL в данном столбце означает, что это первый заказ покупателя.
* Количество заказов равно количеству строк датафрейма. Таким образом, `orer_id` уникально для каждой строки датафрейма и является первичным ключом.
* Количество первых заказов равно количеству уникальных пользователей. 
* Доля первых заказов составляет 7,55% от общего количества заказов. Таким образом, более 90% строк датафрейма это повторные заказы.
* Столбец `device_type_canonical` имеет тип str. Однако в датафрейме встречается всего 2 значения: 'desktop' и 'mobile'. Можно преобразовать к категориальному типу.
* Столбец `order_id` имеет тип int64, хотя максимальное значение составляет 8'653'108 - можно понизить до uint32, так как нет отрицательных значений.
* Столбец `order_dt` имеет тип datetime64, при этом анализ показывает, что в данном столбце время не указана, только дата. Таким образом, можно привести к типу date.
* В столбце `currency_code` содержится только 2 кода валюты: рубль и казахстанский тенге. Таким образом, необходимо учмитывать код валюты при анализе столбца `revenue`
* Столбец `revenue` имеет тип float64 - можно понизить до float32
* В столбце `revenue` содержатся значения равные 0 (~1,9% от всех данных) и отрицательные значения (~0,13%). Учитывая, что данный столбец отражает выручку от продажи билетов, то можно предположить, что заказы с нулевой выручкой это билеты на бесплатное мероприятие или билеты, например, по промокоду или по какой-то акции. Заказы с отрицательной выручкой могут говорить о том, что это возврат ранее купленных билетов, то есть для возврата оформляется отдельный заказ. Но это так же может быть и технической ошибкой. Для корректного вывода необходимо провести дополнительный анализ.
* Столбец `tickets_count` имеет тип int64. При этом в данном поле значения  содержаться от 1 до 57, отрицательные значения отсутствуют. Можно преобразовать к типу uint8 (беззнаковое 8-битное целое).
* Столбец `days_since_prev` имеет тип float64, однако значения встречаются в диапазоне от 0 до 148. Поскольку в данном столбце встречаются значения NULL, то можно преобразовать к типу UInt8 (nullable-тип pandas).
* Столбец `event_id` имеет тип int64 можно преобразовать к uint32, отрицательных значений нет.
* Столбец `event_type_main` содержит значения: 'выставки', 'другое', 'концерты', 'спорт', 'стендап', 'театр', 'ёлки'. Можно преобразовать к категориальному типу данных, вместо str
* Столбцы `service_name`, `region_name` и `city_name` могут содержать неявные дубликаты - необходимо проверить на этапе предобработки данных.

Таким образом, данные датафрейма корректны.

<a id="section2"></a>
---

###  2. Предобработка данных

Выполните все стандартные действия по предобработке данных:

---

**Задача 2.1:** Данные о выручке сервиса представлены в российских рублях и казахстанских тенге. Приведите выручку к единой валюте — российскому рублю.

Для этого используйте датасет с информацией о курсе казахстанского тенге по отношению к российскому рублю за 2024 год — `final_tickets_tenge_df.csv`. Его можно загрузить по пути `https://code.s3.yandex.net/datasets/final_tickets_tenge_df.csv')`

Значения в рублях представлено для 100 тенге.

Результаты преобразования сохраните в новый столбец `revenue_rub`.

---

In [14]:
# Получим данные о курсе рубля и тенге
df_curr_rates = pd.read_csv('https://code.s3.yandex.net/datasets/final_tickets_tenge_df.csv')
df_curr_rates.info()

<class 'pandas.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   data     357 non-null    str
 1   nominal  357 non-null    int64
 2   curs     357 non-null    float64
 3   cdx      357 non-null    str
dtypes: float64(1), int64(1), str(2)
memory usage: 11.3 KB

In [15]:
df_curr_rates.head(10)

         data  nominal     curs  cdx
0  2024-01-10      100  19.9391  kzt
1  2024-01-11      100  19.7255  kzt
2  2024-01-12      100  19.5839  kzt
3  2024-01-13      100  19.4501  kzt
4  2024-01-14      100  19.4501  kzt
5  2024-01-15      100  19.4501  kzt
6  2024-01-16      100  19.4264  kzt
7  2024-01-17      100  19.4177  kzt
8  2024-01-18      100  19.5798  kzt
9  2024-01-19      100  19.5741  kzt

In [16]:
# Преобразуем столбец `data` из str в date
df_curr_rates['data'] = pd.to_datetime(df_curr_rates['data'])
df_curr_rates.info()

<class 'pandas.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   data     357 non-null    datetime64[us]
 1   nominal  357 non-null    int64
 2   curs     357 non-null    float64
 3   cdx      357 non-null    str
dtypes: datetime64[us](1), float64(1), int64(1), str(1)
memory usage: 11.3 KB

---

**Задача 2.2:**

- Проверьте данные на пропущенные значения. Если выгрузка из SQL была успешной, то пропуски должны быть только в столбце `days_since_prev`.
- Преобразуйте типы данных в некоторых столбцах, если это необходимо. Обратите внимание на данные с датой и временем, а также на числовые данные, размерность которых можно сократить.
- Изучите значения в ключевых столбцах. Обработайте ошибки, если обнаружите их.
    - Проверьте, какие категории указаны в столбцах с номинальными данными. Есть ли среди категорий такие, что обозначают пропуски в данных или отсутствие информации? Проведите нормализацию данных, если это необходимо.
    - Проверьте распределение численных данных и наличие в них выбросов. Для этого используйте статистические показатели, гистограммы распределения значений или диаграммы размаха.
        
        Важные показатели в рамках поставленной задачи — это выручка с заказа (`revenue_rub`) и количество билетов в заказе (`tickets_count`), поэтому в первую очередь проверьте данные в этих столбцах.
        
        Если обнаружите выбросы в поле `revenue_rub`, то отфильтруйте значения по 99 перцентилю.

После предобработки проверьте, были ли отфильтрованы данные. Если были, то оцените, в каком объёме. Сформулируйте промежуточный вывод, зафиксировав основные действия и описания новых столбцов.

---

In [17]:
# Приведем столбцы к нужному типу данных.
df[['device_type_canonical', 'event_type_main']] = df[['device_type_canonical', 'event_type_main']].astype('category')
df[['order_id', 'event_id']] = df[['order_id', 'event_id']].astype('uint32')
df['revenue'] = df['revenue'].astype('float32')
df['tickets_count'] = df['tickets_count'].astype('uint8')
df['days_since_prev'] = df['days_since_prev'].astype('UInt8')
df['order_dt'] = df['order_dt'].dt.date

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 290611 entries, 0 to 290610
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   user_id                290611 non-null  str
 1   device_type_canonical  290611 non-null  category
 2   order_id               290611 non-null  uint32
 3   order_dt               290611 non-null  object
 4   order_ts               290611 non-null  datetime64[us]
 5   currency_code          290611 non-null  str
 6   revenue                290611 non-null  float32
 7   tickets_count          290611 non-null  uint8
 8   days_since_prev        268678 non-null  UInt8
 9   event_id               290611 non-null  uint32
 10  service_name           290611 non-null  str
 11  event_type_main        290611 non-null  category
 12  region_name            290611 non-null  str
 13  city_name              290611 non-null  str
dtypes: UInt8(1), category(2), datetime64[us](1), float32(1), object(1), str(5), uint32(2), uint8(1)
memory usage: 20.2+ MB

---
<a id="section3"></a>
### 3. Создание профиля пользователя

В будущем отдел маркетинга планирует создать модель для прогнозирования возврата пользователей. Поэтому сейчас они просят вас построить агрегированные признаки, описывающие поведение и профиль каждого пользователя.

---

**Задача 3.1.** Постройте профиль пользователя — для каждого пользователя найдите:

- дату первого и последнего заказа;
- устройство, с которого был сделан первый заказ;
- регион, в котором был сделан первый заказ;
- билетного партнёра, к которому обращались при первом заказе;
- жанр первого посещённого мероприятия (используйте поле `event_type_main`);
- общее количество заказов;
- средняя выручка с одного заказа в рублях;
- среднее количество билетов в заказе;
- среднее время между заказами.

После этого добавьте два бинарных признака:

- `is_two` — совершил ли пользователь 2 и более заказа;
- `is_five` — совершил ли пользователь 5 и более заказов.

**Рекомендация:** перед тем как строить профиль, отсортируйте данные по времени совершения заказа.

---

---

**Задача 3.2.** Прежде чем проводить исследовательский анализ данных и делать выводы, важно понять, с какими данными вы работаете: насколько они репрезентативны и нет ли в них аномалий.

Используя данные о профилях пользователей, рассчитайте:

- общее число пользователей в выборке;
- среднюю выручку с одного заказа;
- долю пользователей, совершивших 2 и более заказа;
- долю пользователей, совершивших 5 и более заказов.

Также изучите статистические показатели:

- по общему числу заказов;
- по среднему числу билетов в заказе;
- по среднему количеству дней между покупками.

По результатам оцените данные: достаточно ли их по объёму, есть ли аномальные значения в данных о количестве заказов и среднем количестве билетов?

Если вы найдёте аномальные значения, опишите их и примите обоснованное решение о том, как с ними поступить:

- Оставить и учитывать их при анализе?
- Отфильтровать данные по какому-то значению, например, по 95-му или 99-му перцентилю?

Если вы проведёте фильтрацию, то вычислите объём отфильтрованных данных и выведите статистические показатели по обновлённому датасету.

---

### 4. Исследовательский анализ данных

Следующий этап — исследование признаков, влияющих на возврат пользователей, то есть на совершение повторного заказа. Для этого используйте профили пользователей.

<a id="section4"></a>

#### 4.1. Исследование признаков первого заказа и их связи с возвращением на платформу
<a id="section41"></a>
Исследуйте признаки, описывающие первый заказ пользователя, и выясните, влияют ли они на вероятность возвращения пользователя.

---

**Задача 4.1.1.** Изучите распределение пользователей по признакам.

- Сгруппируйте пользователей:
    - по типу их первого мероприятия;
    - по типу устройства, с которого совершена первая покупка;
    - по региону проведения мероприятия из первого заказа;
    - по билетному оператору, продавшему билеты на первый заказ.
- Подсчитайте общее количество пользователей в каждом сегменте и их долю в разрезе каждого признака. Сегмент — это группа пользователей, объединённых определённым признаком, то есть объединённые принадлежностью к категории. Например, все клиенты, сделавшие первый заказ с мобильного телефона, — это сегмент.
- Ответьте на вопрос: равномерно ли распределены пользователи по сегментам или есть выраженные «точки входа» — сегменты с наибольшим числом пользователей?

---

---

**Задача 4.1.2.** Проанализируйте возвраты пользователей:

- Для каждого сегмента вычислите долю пользователей, совершивших два и более заказа.
- Визуализируйте результат подходящим графиком. Если сегментов слишком много, то поместите на график только 10 сегментов с наибольшим количеством пользователей. Такое возможно с сегментами по региону и по билетному оператору.
- Ответьте на вопросы:
    - Какие сегменты пользователей чаще возвращаются на Яндекс Афишу?
    - Наблюдаются ли успешные «точки входа» — такие сегменты, в которых пользователи чаще совершают повторный заказ, чем в среднем по выборке?

При интерпретации результатов учитывайте размер сегментов: если в сегменте мало пользователей (например, десятки), то доли могут быть нестабильными и недостоверными, то есть показывать широкую вариацию значений.

---

---

**Задача 4.1.3.** Опираясь на выводы из задач выше, проверьте продуктовые гипотезы:

- **Гипотеза 1.** Тип мероприятия влияет на вероятность возврата на Яндекс Афишу: пользователи, которые совершили первый заказ на спортивные мероприятия, совершают повторный заказ чаще, чем пользователи, оформившие свой первый заказ на концерты.
- **Гипотеза 2.** В регионах, где больше всего пользователей посещают мероприятия, выше доля повторных заказов, чем в менее активных регионах.

---

---
<a id="section42"></a>
#### 4.2. Исследование поведения пользователей через показатели выручки и состава заказа

Изучите количественные характеристики заказов пользователей, чтобы узнать среднюю выручку сервиса с заказа и количество билетов, которое пользователи обычно покупают.

Эти метрики важны не только для оценки выручки, но и для оценки вовлечённости пользователей. Возможно, пользователи с более крупными и дорогими заказами более заинтересованы в сервисе и поэтому чаще возвращаются.

---

**Задача 4.2.1.** Проследите связь между средней выручкой сервиса с заказа и повторными заказами.

- Постройте сравнительные гистограммы распределения средней выручки с билета (`avg_revenue_rub`):
    - для пользователей, совершивших один заказ;
    - для вернувшихся пользователей, совершивших 2 и более заказа.
- Ответьте на вопросы:
    - В каких диапазонах средней выручки концентрируются пользователи из каждой группы?
    - Есть ли различия между группами?

Текст на сером фоне:
    
**Рекомендация:**

1. Используйте одинаковые интервалы (`bins`) и прозрачность (`alpha`), чтобы визуально сопоставить распределения.
2. Задайте параметру `density` значение `True`, чтобы сравнивать форму распределений, даже если число пользователей в группах отличается.

---

---

**Задача 4.2.2.** Сравните распределение по средней выручке с заказа в двух группах пользователей:

- совершившие 2–4 заказа;
- совершившие 5 и более заказов.

Ответьте на вопрос: есть ли различия по значению средней выручки с заказа между пользователями этих двух групп?

---

---

**Задача 4.2.3.** Проанализируйте влияние среднего количества билетов в заказе на вероятность повторной покупки.

- Изучите распределение пользователей по среднему количеству билетов в заказе (`avg_tickets_count`) и опишите основные наблюдения.
- Разделите пользователей на несколько сегментов по среднему количеству билетов в заказе:
    - от 1 до 2 билетов;
    - от 2 до 3 билетов;
    - от 3 до 5 билетов;
    - от 5 и более билетов.
- Для каждого сегмента подсчитайте общее число пользователей и долю пользователей, совершивших повторные заказы.
- Ответьте на вопросы:
    - Как распределены пользователи по сегментам — равномерно или сконцентрировано?
    - Есть ли сегменты с аномально высокой или низкой долей повторных покупок?

---

---
<a id="section43"></a>
#### 4.3. Исследование временных характеристик первого заказа и их влияния на повторные покупки

Изучите временные параметры, связанные с первым заказом пользователей:

- день недели первой покупки;
- время с момента первой покупки — лайфтайм;
- средний интервал между покупками пользователей с повторными заказами.

---

**Задача 4.3.1.** Проанализируйте, как день недели, в которой была совершена первая покупка, влияет на поведение пользователей.

- По данным даты первого заказа выделите день недели.
- Для каждого дня недели подсчитайте общее число пользователей и долю пользователей, совершивших повторные заказы. Результаты визуализируйте.
- Ответьте на вопрос: влияет ли день недели, в которую совершена первая покупка, на вероятность возврата клиента?

---

---

**Задача 4.3.2.** Изучите, как средний интервал между заказами влияет на удержание клиентов.

- Рассчитайте среднее время между заказами для двух групп пользователей:
    - совершившие 2–4 заказа;
    - совершившие 5 и более заказов.
- Исследуйте, как средний интервал между заказами влияет на вероятность повторного заказа, и сделайте выводы.

---

---
<a id="section44"></a>
#### 4.4. Корреляционный анализ количества покупок и признаков пользователя

Изучите, какие характеристики первого заказа и профиля пользователя могут быть связаны с числом покупок. Для этого используйте универсальный коэффициент корреляции `phi_k`, который позволяет анализировать как числовые, так и категориальные признаки.

---

**Задача 4.4.1:** Проведите корреляционный анализ:
- Рассчитайте коэффициент корреляции `phi_k` между признаками профиля пользователя и числом заказов (`total_orders`). При необходимости используйте параметр `interval_cols` для определения интервальных данных.
- Проанализируйте полученные результаты. Если полученные значения будут близки к нулю, проверьте разброс данных в `total_orders`. Такое возможно, когда в данных преобладает одно значение: в таком случае корреляционный анализ может показать отсутствие связей. Чтобы этого избежать, выделите сегменты пользователей по полю `total_orders`, а затем повторите корреляционный анализ. Выделите такие сегменты:
    - 1 заказ;
    - от 2 до 4 заказов;
    - от 5 и выше.
- Визуализируйте результат корреляции с помощью тепловой карты.
- Ответьте на вопрос: какие признаки наиболее связаны с количеством заказов?

---

<a id="section5"></a>
### 5. Общий вывод и рекомендации

В конце проекта напишите общий вывод и рекомендации: расскажите заказчику, на что нужно обратить внимание. В выводах кратко укажите:

- **Информацию о данных**, с которыми вы работали, и то, как они были подготовлены: например, расскажите о фильтрации данных, переводе тенге в рубли, фильтрации выбросов.
- **Основные результаты анализа.** Например, укажите:
    - Сколько пользователей в выборке? Как распределены пользователи по числу заказов? Какие ещё статистические показатели вы подсчитали важным во время изучения данных?
    - Какие признаки первого заказа связаны с возвратом пользователей?
    - Как связаны средняя выручка и количество билетов в заказе с вероятностью повторных покупок?
    - Какие временные характеристики влияют на удержание (день недели, интервалы между покупками)?
    - Какие характеристики первого заказа и профиля пользователя могут быть связаны с числом покупок согласно результатам корреляционного анализа?
- Дополните выводы информацией, которая покажется вам важной и интересной. Следите за общим объёмом выводов — они должны быть компактными и ёмкими.

В конце предложите заказчику рекомендации о том, как именно действовать в его ситуации. Например, укажите, на какие сегменты пользователей стоит обратить внимание в первую очередь, а какие нуждаются в дополнительных маркетинговых усилиях.

### 6. Финализация проекта и публикация в Git

Когда вы закончите анализировать данные, оформите проект, а затем опубликуйте его.

Выполните следующие действия:

1. Создайте файл `.gitignore`. Добавьте в него все временные и чувствительные файлы, которые не должны попасть в репозиторий.
2. Сформируйте файл `requirements.txt`. Зафиксируйте все библиотеки, которые вы использовали в проекте.
3. Вынести все чувствительные данные (параметры подключения к базе) в `.env`файл.
4. Проверьте, что проект запускается и воспроизводим.
5. Загрузите проект в публичный репозиторий — например, на GitHub. Убедитесь, что все нужные файлы находятся в репозитории, исключая те, что в `.gitignore`. Ссылка на репозиторий понадобится для отправки проекта на проверку. Вставьте её в шаблон проекта в тетрадке Jupyter Notebook перед отправкой проекта на ревью.

**Вставьте ссылку на проект в этой ячейке тетрадки перед отправкой проекта на ревью.**